//! Build script — reads tools.toml and generates:
//!   src/mcp/generated_schema.rs  — MCP tool list JSON
//!   src/cli/generated_help.rs    — CLI help string constants
//!   templates/SKILL.md           — Claude Code skill documentation

use indexmap::IndexMap;
use serde::Deserialize;
use std::fs;
use std::path::Path;

#[derive(Deserialize)]
struct ToolsToml {
    skill: Option<SkillConfig>,
    tools: IndexMap<String, ToolDef>,
}

#[derive(Deserialize)]
struct SkillConfig {
    workflow: String,
}

#[derive(Deserialize)]
struct ToolDef {
    cli_name: String,
    mcp_description: String,
    cli_about: String,
    #[serde(default)]
    params: Vec<ParamDef>,
}

#[derive(Deserialize)]
struct ParamDef {
    name: String,
    #[serde(rename = "type")]
    type_: String,
    #[serde(default)]
    required: bool,
    #[serde(rename = "enum")]
    enum_values: Option<Vec<String>>,
    mcp_description: String,
    cli_help: Option<String>,
    #[allow(dead_code)]
    cli_flag: Option<String>,
}

fn main() {
    println!("cargo:rerun-if-changed=tools.toml");
    println!("cargo:rerun-if-changed=build.rs");

    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let tools_toml_path = Path::new(&manifest_dir).join("tools.toml");

    let content = fs::read_to_string(&tools_toml_path)
        .unwrap_or_else(|e| panic!("Failed to read tools.toml: {e}"));

    let parsed: ToolsToml =
        toml::from_str(&content).unwrap_or_else(|e| panic!("Failed to parse tools.toml: {e}"));

    // Generate all three outputs.
    let schema_rs = generate_mcp_schema(&parsed.tools);
    let help_rs = generate_cli_help(&parsed.tools);
    let skill_md = generate_skill_md(parsed.skill.as_ref(), &parsed.tools);

    write_if_changed(
        &Path::new(&manifest_dir).join("src/mcp/generated_schema.rs"),
        &schema_rs,
    );
    write_if_changed(
        &Path::new(&manifest_dir).join("src/cli/generated_help.rs"),
        &help_rs,
    );
    write_if_changed(
        &Path::new(&manifest_dir).join("templates/SKILL.md"),
        &skill_md,
    );
}

/// Only write if the content has changed to avoid spurious rebuilds.
fn write_if_changed(path: &Path, content: &str) {
    if let Ok(existing) = fs::read_to_string(path) {
        if existing == content {
            return;
        }
    }
    fs::write(path, content).unwrap_or_else(|e| panic!("Failed to write {}: {e}", path.display()));
}

// ---------------------------------------------------------------------------
// MCP schema generator
// ---------------------------------------------------------------------------

fn generate_mcp_schema(tools: &IndexMap<String, ToolDef>) -> String {
    let mut tool_jsons = Vec::new();

    for (tool_name, tool) in tools {
        let mut properties = serde_json::Map::new();
        let mut required: Vec<String> = Vec::new();

        for param in &tool.params {
            let mut prop = serde_json::Map::new();
            prop.insert(
                "type".to_string(),
                serde_json::Value::String(param.type_.clone()),
            );
            prop.insert(
                "description".to_string(),
                serde_json::Value::String(param.mcp_description.clone()),
            );
            if let Some(ev) = &param.enum_values {
                prop.insert(
                    "enum".to_string(),
                    serde_json::Value::Array(
                        ev.iter()
                            .map(|s| serde_json::Value::String(s.clone()))
                            .collect(),
                    ),
                );
            }
            properties.insert(param.name.clone(), serde_json::Value::Object(prop));

            if param.required {
                required.push(param.name.clone());
            }
        }

        let mut input_schema = serde_json::json!({
            "type": "object",
            "properties": properties
        });
        if !required.is_empty() {
            input_schema["required"] = serde_json::Value::Array(
                required
                    .into_iter()
                    .map(serde_json::Value::String)
                    .collect(),
            );
        }

        tool_jsons.push(serde_json::json!({
            "name": tool_name,
            "description": tool.mcp_description,
            "inputSchema": input_schema
        }));
    }

    let json_val = serde_json::json!({ "tools": tool_jsons });
    let json_str = serde_json::to_string_pretty(&json_val).expect("JSON serialization failed");

    format!(
        "// AUTO-GENERATED by build.rs from tools.toml — do not edit\n\
         #![allow(clippy::all)]\n\
         #[rustfmt::skip]\n\
         \n\
         pub fn generated_tool_list() -> serde_json::Value {{\n\
             serde_json::from_str(r##\"{}\"##).expect(\"generated tool list is valid JSON\")\n\
         }}\n",
        json_str
    )
}

// ---------------------------------------------------------------------------
// CLI help constants generator
// ---------------------------------------------------------------------------

fn generate_cli_help(tools: &IndexMap<String, ToolDef>) -> String {
    let mut lines = vec![
        "// AUTO-GENERATED by build.rs from tools.toml — do not edit".to_string(),
        "#![allow(dead_code, unused)]".to_string(),
        "#![allow(clippy::all)]".to_string(),
    ];

    for tool in tools.values() {
        let prefix = tool.cli_name.to_uppercase().replace('-', "_");

        // Command-level about constant.
        let escaped = rust_escape(&tool.cli_about);
        lines.push(format!("pub const {prefix}_ABOUT: &str = \"{escaped}\";"));

        // Per-param help constants.
        for param in &tool.params {
            if let Some(help) = &param.cli_help {
                let param_upper = param.name.to_uppercase().replace('-', "_");
                let escaped = rust_escape(help);
                lines.push(format!(
                    "pub const {prefix}_{param_upper}_HELP: &str = \"{escaped}\";"
                ));
            }
        }

        lines.push(String::new());
    }

    lines.join("\n")
}

/// Escape a string for embedding in a Rust double-quoted string literal.
fn rust_escape(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

// ---------------------------------------------------------------------------
// SKILL.md generator
// ---------------------------------------------------------------------------

fn generate_skill_md(skill: Option<&SkillConfig>, tools: &IndexMap<String, ToolDef>) -> String {
    let mut out = String::new();

    out.push_str("---\n");
    out.push_str("name: fmm-navigate\n");
    out.push_str("description: \"This project uses fmm (.fmmrc.json) for code metadata. INVOKE THIS SKILL before reading or searching source files — it provides the MCP-first navigation protocol that replaces grep/read with O(1) lookups.\"\n");
    out.push_str("---\n\n");
    out.push_str("# fmm — MCP-First Code Navigation\n\n");
    out.push_str("This codebase has FMM metadata available via MCP tools. Use them for instant, structured lookups instead of grep/read.\n\n");

    // MCP tools reference table.
    out.push_str("## MCP Tools (ALWAYS USE THESE FIRST)\n\n");
    out.push_str("| Tool | Use Case | When to Use |\n");
    out.push_str("|------|----------|-------------|\n");

    let use_cases = [
        (
            "fmm_list_files",
            "Orient to codebase structure",
            "Start here — highest blast-radius first with sort_by: \"downstream\"",
        ),
        (
            "fmm_lookup_export",
            "Find where a symbol is defined",
            "O(1) lookup — replaces grep for symbol location",
        ),
        (
            "fmm_file_outline",
            "Understand file structure",
            "Table-of-contents before reading anything",
        ),
        (
            "fmm_read_symbol",
            "Read source for a symbol",
            "Surgical extraction — one call, exact lines",
        ),
        (
            "fmm_list_exports",
            "Fuzzy export discovery",
            "Find exports matching a pattern or in a directory",
        ),
        (
            "fmm_dependency_graph",
            "Impact analysis",
            "Upstream deps + downstream blast radius",
        ),
        (
            "fmm_search",
            "Multi-criteria search",
            "AND queries: imports X, size > N, exports Y",
        ),
        (
            "fmm_glossary",
            "Symbol-level blast radius",
            "All definitions + who imports each — before renaming",
        ),
    ];

    for (tool_name, use_case, when) in &use_cases {
        out.push_str(&format!(
            "| `mcp__fmm__{tool_name}` | {use_case} | {when} |\n"
        ));
    }
    out.push('\n');

    // Workflow section.
    if let Some(skill) = skill {
        out.push_str(skill.workflow.trim_start_matches('\n'));
        out.push('\n');
    }

    // Per-tool parameter reference tables.
    out.push_str("\n## Parameter Reference\n\n");
    out.push_str("> Auto-generated from tools.toml — all options for each tool.\n\n");

    for (tool_name, tool) in tools {
        out.push_str(&format!("### `{tool_name}`\n\n"));
        out.push_str(&format!("{}\n\n", tool.mcp_description));

        if !tool.params.is_empty() {
            out.push_str("| Parameter | Type | Required | Description |\n");
            out.push_str("|-----------|------|----------|-------------|\n");

            for param in &tool.params {
                let req = if param.required { "yes" } else { "no" };
                let type_str = if let Some(ev) = &param.enum_values {
                    let opts = ev.join(" \\| ");
                    format!("enum: {opts}")
                } else {
                    param.type_.clone()
                };
                // Truncate description for table readability.
                let desc = if param.mcp_description.len() > 120 {
                    format!("{}...", &param.mcp_description[..117])
                } else {
                    param.mcp_description.clone()
                };
                out.push_str(&format!(
                    "| `{}` | {} | {} | {} |\n",
                    param.name, type_str, req, desc
                ));
            }
            out.push('\n');
        }
    }

    // Rules section.
    out.push_str("## Rules\n\n");
    out.push_str("1. **`fmm_list_files(sort_by: \"downstream\")` IS YOUR STARTING POINT** — always orient before diving in.\n");
    out.push_str("2. **`fmm_read_symbol` IS YOUR DEFAULT** — need to see code? Use it. One call, exact lines, zero waste.\n");
    out.push_str("3. **`fmm_file_outline` BEFORE READING** — see the shape of a file before deciding what to read.\n");
    out.push_str("4. **MCP TOOLS ARE PRIMARY** — always call `fmm_*` tools before grep/read.\n");
    out.push_str(
        "5. **STRUCTURED > UNSTRUCTURED** — MCP returns parsed data, grep returns text.\n",
    );
    out.push_str("6. **READ SOURCE ONLY WHEN EDITING** — sidecars/MCP tell you what you need for navigation.\n\n");

    // Fallback section.
    out.push_str("## Sidecar Fallback\n\n");
    out.push_str("If MCP tools are unavailable, sidecar files exist at `filename.ext.fmm`:\n\n");
    out.push_str("```yaml\n");
    out.push_str("file: src/core/pipeline.ts\n");
    out.push_str("fmm: v0.3\n");
    out.push_str("exports:\n");
    out.push_str("  createPipeline: [10, 45]\n");
    out.push_str("  PipelineConfig: [47, 52]\n");
    out.push_str("imports: [zod, lodash]\n");
    out.push_str("dependencies: [./engine, ./validators, ../utils/logger]\n");
    out.push_str("loc: 142\n");
    out.push_str("```\n\n");
    out.push_str("Use `Grep \"exports:\" **/*.fmm` as fallback when MCP is not available.\n");

    out
}
