// AUTO-GENERATED by build.rs from tools.toml — do not edit
#![allow(dead_code, unused)]
#![allow(clippy::all)]
pub const LOOKUP_ABOUT: &str = "Find which file defines a symbol and show its metadata.\n\nUses the pre-built export index for O(1) lookup. Supports plain exports, re-exports, and dotted ClassName.method notation.";
pub const LOOKUP_NAME_HELP: &str = "Symbol name to look up (exact match; use 'fmm exports <term>' for fuzzy)";

pub const EXPORTS_ABOUT: &str = "List exports matching a pattern across the indexed codebase.\n\nWithout a pattern, lists all exports grouped by file. Use --dir to scope results to a directory. Includes dotted method names (ClassName.method).\n\nPattern matching is auto-detected: plain strings use case-insensitive substring match; patterns with regex metacharacters (^, $, [, (, \\\\, ., *, +, ?, {) are compiled as regex.";
pub const EXPORTS_PATTERN_HELP: &str = "Pattern to filter exports — substring (case-insensitive) or regex (auto-detected when metacharacters present)";
pub const EXPORTS_FILE_HELP: &str = "File path — returns all exports from this file";
pub const EXPORTS_DIRECTORY_HELP: &str = "Scope results to a directory prefix (e.g. packages/core/)";
pub const EXPORTS_LIMIT_HELP: &str = "Maximum number of results (default: 200)";
pub const EXPORTS_OFFSET_HELP: &str = "Number of results to skip (default: 0) — use for pagination";

pub const DEPS_ABOUT: &str = "Show a file's dependency graph: local_deps (resolved local imports), external (packages), and downstream (what would break if this file changes).\n\nUse --depth for transitive traversal. depth=-1 computes the full closure.\nUse --filter=source to exclude test files from downstream for production blast-radius analysis.";
pub const DEPS_FILE_HELP: &str = "Source file path (relative to project root, as indexed by fmm)";
pub const DEPS_DEPTH_HELP: &str = "Traversal depth (1 = direct deps only, -1 = full closure)";
pub const DEPS_FILTER_HELP: &str = "Filter upstream/downstream by file type: all (default), source (exclude tests), tests (only tests)";

pub const READ_ABOUT: &str = "Read the source code of an exported symbol or a specific method.\n\nUse plain name for a top-level export, or ClassName.method notation for a specific public method. Truncates at 10KB by default; use --no-truncate for full source.";
pub const READ_NAME_HELP: &str = "Symbol name (or ClassName.method for a specific public method)";
pub const READ_TRUNCATE_HELP: &str = "Return full source, bypassing the 10KB truncation cap";
pub const READ_LINE_NUMBERS_HELP: &str = "Prepend absolute line numbers to each source line";

pub const OUTLINE_ABOUT: &str = "Show all exports in a file with their line ranges.\n\nUse before reading source to identify which symbol to target with 'fmm read'.";
pub const OUTLINE_FILE_HELP: &str = "Source file path (relative to project root)";
pub const OUTLINE_INCLUDE_PRIVATE_HELP: &str = "Include private/protected methods and fields under each class";

pub const SEARCH_ABOUT: &str = "Query the index — O(1) export lookup, dependency graphs, LOC filters.\n\nWith a bare term (no flags), searches across all dimensions: exports, file paths, and imports — with smart ranking. Exact export matches appear first.\n\nExport lookups use a reverse index for O(1) performance. Flags narrow the search to a single dimension and can be combined with AND logic.";
pub const SEARCH_TERM_HELP: &str = "Search term — searches exports, files, and imports (smart ranking)";
pub const SEARCH_EXPORT_HELP: &str = "Find file by export name (exact O(1) + fuzzy substring)";
pub const SEARCH_IMPORTS_HELP: &str = "Find files that import a module";
pub const SEARCH_DEPENDS_ON_HELP: &str = "Find files that depend on a path";
pub const SEARCH_MIN_LOC_HELP: &str = "Minimum lines of code";
pub const SEARCH_MAX_LOC_HELP: &str = "Maximum lines of code";
pub const SEARCH_LIMIT_HELP: &str = "Maximum number of fuzzy export results (default: 50)";

pub const LS_ABOUT: &str = "List all files indexed by fmm under a directory prefix.\n\nShows file paths with LOC and export count.\n\nSort modes (--sort-by):\n- loc (default): heaviest files first\n- name: alphabetical\n- exports: most exported symbols first\n- downstream: most depended-upon files first (best for pre-refactoring blast radius)\n- modified: most recently changed first\n\nUse --group-by=subdir to collapse into directory buckets.\nUse --filter=source to exclude test files; --filter=tests for test files only.";
pub const LS_DIRECTORY_HELP: &str = "Directory prefix to filter (e.g. src/, packages/core/)";
pub const LS_PATTERN_HELP: &str = "Glob pattern to filter by filename (e.g. '*.ts', '*.rs', 'test_*')";
pub const LS_LIMIT_HELP: &str = "Maximum number of files to return (default: 200)";
pub const LS_OFFSET_HELP: &str = "Number of files to skip (default: 0) — use for pagination";
pub const LS_SORT_BY_HELP: &str = "Sort field: loc (default), name, exports, downstream, modified";
pub const LS_ORDER_HELP: &str = "Sort order: asc or desc (default depends on sort-by)";
pub const LS_GROUP_BY_HELP: &str = "Collapse files into directory buckets (subdir: group by immediate subdirectory)";
pub const LS_FILTER_HELP: &str = "File type filter: all (default), source (exclude tests), tests (only tests)";

pub const GLOSSARY_ABOUT: &str = "Symbol-level impact analysis.\n\nGiven a symbol name or pattern, shows every definition and exactly which files import it. Use before renaming a function or changing a signature to know precisely what breaks.";
pub const GLOSSARY_PATTERN_HELP: &str = "Symbol name or substring pattern (case-insensitive)";
pub const GLOSSARY_LIMIT_HELP: &str = "Maximum number of entries returned (default: 10)";
pub const GLOSSARY_MODE_HELP: &str = "Filter mode: source (default, no tests), tests (test coverage only), all (unfiltered)";
pub const GLOSSARY_PRECISION_HELP: &str = "Precision level: named (default, fast) or call-site (tree-sitter verification)";
