//! Build script — reads tools.toml and generates:
//!   src/mcp/generated_schema.rs  — MCP tool list JSON
//!   src/cli/generated_help.rs    — CLI help string constants

use indexmap::IndexMap;
use serde::Deserialize;
use std::fs;
use std::path::Path;

#[derive(Deserialize)]
struct ToolsToml {
    #[allow(dead_code)]
    skill: Option<toml::Value>,
    tools: IndexMap<String, ToolDef>,
}

#[derive(Deserialize)]
struct ToolDef {
    cli_name: String,
    mcp_description: String,
    cli_about: String,
    #[serde(default)]
    params: Vec<ParamDef>,
}

#[derive(Deserialize)]
struct ParamDef {
    name: String,
    #[serde(rename = "type")]
    type_: String,
    #[serde(default)]
    required: bool,
    #[serde(rename = "enum")]
    enum_values: Option<Vec<String>>,
    mcp_description: String,
    cli_help: Option<String>,
    #[allow(dead_code)]
    cli_flag: Option<String>,
}

fn main() {
    println!("cargo:rerun-if-changed=tools.toml");
    println!("cargo:rerun-if-changed=build.rs");

    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let tools_toml_path = Path::new(&manifest_dir).join("tools.toml");

    let content = fs::read_to_string(&tools_toml_path)
        .unwrap_or_else(|e| panic!("Failed to read tools.toml: {e}"));

    let parsed: ToolsToml =
        toml::from_str(&content).unwrap_or_else(|e| panic!("Failed to parse tools.toml: {e}"));

    let schema_rs = generate_mcp_schema(&parsed.tools);
    let help_rs = generate_cli_help(&parsed.tools);

    write_if_changed(
        &Path::new(&manifest_dir).join("src/mcp/generated_schema.rs"),
        &schema_rs,
    );
    write_if_changed(
        &Path::new(&manifest_dir).join("src/cli/generated_help.rs"),
        &help_rs,
    );
}

/// Only write if the content has changed to avoid spurious rebuilds.
fn write_if_changed(path: &Path, content: &str) {
    if let Ok(existing) = fs::read_to_string(path)
        && existing == content
    {
        return;
    }
    fs::write(path, content).unwrap_or_else(|e| panic!("Failed to write {}: {e}", path.display()));
}

// ---------------------------------------------------------------------------
// MCP schema generator
// ---------------------------------------------------------------------------

fn generate_mcp_schema(tools: &IndexMap<String, ToolDef>) -> String {
    let mut tool_jsons = Vec::new();

    for (tool_name, tool) in tools {
        let mut properties = serde_json::Map::new();
        let mut required: Vec<String> = Vec::new();

        for param in &tool.params {
            let mut prop = serde_json::Map::new();
            prop.insert(
                "type".to_string(),
                serde_json::Value::String(param.type_.clone()),
            );
            prop.insert(
                "description".to_string(),
                serde_json::Value::String(param.mcp_description.clone()),
            );
            if let Some(ev) = &param.enum_values {
                prop.insert(
                    "enum".to_string(),
                    serde_json::Value::Array(
                        ev.iter()
                            .map(|s| serde_json::Value::String(s.clone()))
                            .collect(),
                    ),
                );
            }
            properties.insert(param.name.clone(), serde_json::Value::Object(prop));

            if param.required {
                required.push(param.name.clone());
            }
        }

        let mut input_schema = serde_json::json!({
            "type": "object",
            "properties": properties
        });
        if !required.is_empty() {
            input_schema["required"] = serde_json::Value::Array(
                required
                    .into_iter()
                    .map(serde_json::Value::String)
                    .collect(),
            );
        }

        tool_jsons.push(serde_json::json!({
            "name": tool_name,
            "description": tool.mcp_description,
            "inputSchema": input_schema
        }));
    }

    let json_val = serde_json::json!({ "tools": tool_jsons });
    let json_str = serde_json::to_string_pretty(&json_val).expect("JSON serialization failed");

    format!(
        "// AUTO-GENERATED by build.rs from tools.toml — do not edit\n\
         #![allow(clippy::all)]\n\
         #[rustfmt::skip]\n\
         \n\
         pub fn generated_tool_list() -> serde_json::Value {{\n\
             serde_json::from_str(r##\"{}\"##).expect(\"generated tool list is valid JSON\")\n\
         }}\n",
        json_str
    )
}

// ---------------------------------------------------------------------------
// CLI help constants generator
// ---------------------------------------------------------------------------

fn generate_cli_help(tools: &IndexMap<String, ToolDef>) -> String {
    let mut lines = vec![
        "// AUTO-GENERATED by build.rs from tools.toml — do not edit".to_string(),
        "#![allow(dead_code, unused)]".to_string(),
        "#![allow(clippy::all)]".to_string(),
    ];

    for tool in tools.values() {
        let prefix = tool.cli_name.to_uppercase().replace('-', "_");

        // Command-level about constant.
        let escaped = rust_escape(&tool.cli_about);
        lines.push("#[rustfmt::skip]".to_string());
        lines.push(format!("pub const {prefix}_ABOUT: &str = \"{escaped}\";"));

        // Per-param help constants.
        for param in &tool.params {
            if let Some(help) = &param.cli_help {
                let param_upper = param.name.to_uppercase().replace('-', "_");
                let escaped = rust_escape(help);
                lines.push("#[rustfmt::skip]".to_string());
                lines.push(format!(
                    "pub const {prefix}_{param_upper}_HELP: &str = \"{escaped}\";"
                ));
            }
        }

        lines.push(String::new());
    }

    lines.join("\n")
}

/// Escape a string for embedding in a Rust double-quoted string literal.
fn rust_escape(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}
