//! Shared MCP tool utilities: validation, helpers, and compute functions.

use fmm_core::manifest::Manifest;

/// Return a reference to the lazily-initialised set of reexport hub filenames
/// from the builtin `ParserRegistry`.
///
/// Initialised once on first call; subsequent calls are lock-free reads.
fn builtin_reexport_filenames() -> &'static std::collections::HashSet<String> {
    use std::collections::HashSet;
    use std::sync::OnceLock;
    static FILENAMES: OnceLock<HashSet<String>> = OnceLock::new();
    FILENAMES.get_or_init(|| {
        let registry = fmm_core::parser::ParserRegistry::with_builtins();
        registry
            .descriptors()
            .iter()
            .flat_map(|d| d.reexport_filenames.iter().map(|s| (*s).to_string()))
            .collect()
    })
}

/// Return true if a file path is a conventional re-export hub (index/init file).
/// These files aggregate symbols from sub-modules and are not the definition site.
///
/// Checks against all `reexport_filenames` declared by registered language
/// descriptors. Adding a new language with reexport conventions automatically
/// extends this check.
pub(crate) fn is_reexport_file(file_path: &str) -> bool {
    let filename = file_path.rsplit('/').next().unwrap_or(file_path);
    builtin_reexport_filenames().contains(filename)
}

/// Given that `symbol` was found in a re-export hub, search the manifest for a
/// non-index file that also exports the same symbol, preferring files whose
/// directory path shares the most prefix with `reexport_file`.
///
/// Returns `(concrete_file_path, ExportLines)` or `None` if no candidate found.
pub(crate) fn find_concrete_definition(
    manifest: &Manifest,
    symbol: &str,
    reexport_file: &str,
) -> Option<(String, fmm_core::manifest::ExportLines)> {
    let reexport_dir = reexport_file.rsplit_once('/').map(|(d, _)| d).unwrap_or("");

    let mut candidates: Vec<(String, fmm_core::manifest::ExportLines, usize)> = manifest
        .files
        .iter()
        .filter(|(path, _)| {
            let p = path.as_str();
            p != reexport_file && !is_reexport_file(p)
        })
        .filter_map(|(path, entry)| {
            // Find this symbol in the file's export list
            let idx = entry.exports.iter().position(|e| e == symbol)?;
            // Require line-range data — without it we cannot show source
            let lines = entry
                .export_lines
                .as_ref()
                .and_then(|el| el.get(idx))
                .filter(|l| l.start > 0)?;
            // Shared prefix length as proximity score
            let file_dir = path.rsplit_once('/').map(|(d, _)| d).unwrap_or("");
            let shared = reexport_dir
                .chars()
                .zip(file_dir.chars())
                .take_while(|(a, b)| a == b)
                .count();
            Some((path.clone(), lines.clone(), shared))
        })
        .collect();

    // Sort by proximity descending so closest sibling wins
    candidates.sort_by(|(_, _, a), (_, _, b)| b.cmp(a));
    candidates.into_iter().map(|(f, l, _)| (f, l)).next()
}

/// Return an error if `path` looks like a directory (ends with `/` or resolves to a dir on disk).
/// Provides a helpful message pointing to fmm_list_files.
pub(in crate::mcp) fn validate_not_directory(
    path: &str,
    root: &std::path::Path,
) -> Result<(), String> {
    if path.ends_with('/') || path.ends_with(std::path::MAIN_SEPARATOR) {
        return Err(format!(
            "'{}' is a directory, not a file. Use fmm_list_files(directory: \"{}\") to list its contents.",
            path, path
        ));
    }
    let resolved = root.join(path);
    if resolved.is_dir() {
        return Err(format!(
            "'{}' is a directory, not a file. Use fmm_list_files(directory: \"{}/\") to list its contents.",
            path, path
        ));
    }
    Ok(())
}

/// Compute the possible import path specifiers that a file at `candidate_path` would use
/// when importing from `source_file`. Both paths are manifest-relative (e.g.
/// `packages/react-reconciler/src/ReactFiberHooks.js`).
///
/// Returns relative-path forms (without and with extension) plus, when `workspace_roots` is
/// non-empty, workspace-relative bare specifiers for cross-package imports (e.g.
/// `shared/ReactFeatureFlags`). Bare specifiers are generated by checking whether
/// `source_file` lives under a known workspace package root and using that root's
/// directory name as the package prefix.
///
/// These specifiers are compared against keys in `FileEntry::named_imports` and
/// `FileEntry::namespace_imports`, which store paths as written in the import statement.
pub(crate) fn compute_import_specifiers(
    candidate_path: &str,
    source_file: &str,
    workspace_roots: &[std::path::PathBuf],
    project_root: &std::path::Path,
) -> Vec<String> {
    let candidate_dir = candidate_path
        .rsplit_once('/')
        .map(|(d, _)| d)
        .unwrap_or("");
    let (source_dir, source_filename) = source_file.rsplit_once('/').unwrap_or(("", source_file));
    let source_base = source_filename
        .rsplit_once('.')
        .map(|(b, _)| b)
        .unwrap_or(source_filename);

    let candidate_segs: Vec<&str> = if candidate_dir.is_empty() {
        vec![]
    } else {
        candidate_dir.split('/').collect()
    };
    let source_segs: Vec<&str> = if source_dir.is_empty() {
        vec![]
    } else {
        source_dir.split('/').collect()
    };

    let common = candidate_segs
        .iter()
        .zip(source_segs.iter())
        .take_while(|(a, b)| a == b)
        .count();
    let up = candidate_segs.len() - common;
    let down = &source_segs[common..];

    let mut parts: Vec<&str> = std::iter::repeat_n("..", up).collect();
    parts.extend(down.iter().copied());

    let (base_specifier, ext_specifier) = if parts.is_empty() {
        (
            format!("./{}", source_base),
            format!("./{}", source_filename),
        )
    } else if up == 0 {
        // Down-only path (source is in a subdirectory of the common ancestor).
        // Parts contain no `..` segments, so we must add `./` — without it the
        // specifier would be treated as a bare package name, not a relative path.
        let suffix = parts.join("/");
        (
            format!("./{}/{}", suffix, source_base),
            format!("./{}/{}", suffix, source_filename),
        )
    } else {
        // Up-then-down path — starts with `..`, already unambiguously relative.
        let prefix = parts.join("/");
        (
            format!("{}/{}", prefix, source_base),
            format!("{}/{}", prefix, source_filename),
        )
    };

    let mut specifiers = if base_specifier == ext_specifier {
        vec![base_specifier]
    } else {
        vec![base_specifier, ext_specifier]
    };

    // Workspace-relative bare specifiers for cross-package imports.
    // In pnpm/npm workspace monorepos, cross-package imports are written as bare specifiers
    // (e.g. `shared/ReactFeatureFlags`) rather than relative paths. Generate these by
    // checking whether source_file lives under a known workspace package root and using
    // that root's directory name as the package prefix.
    if !workspace_roots.is_empty() {
        let abs_source = project_root.join(source_file);
        for ws_root in workspace_roots {
            if let Ok(rel_within_pkg) = abs_source.strip_prefix(ws_root)
                && let Some(pkg_name) = ws_root.file_name()
            {
                let pkg_name_str = pkg_name.to_string_lossy();
                let rel_str = rel_within_pkg.to_string_lossy();
                let with_ext = format!("{}/{}", pkg_name_str, rel_str);
                let without_ext = format!(
                    "{}/{}",
                    pkg_name_str,
                    rel_within_pkg.with_extension("").to_string_lossy()
                );
                if !specifiers.contains(&with_ext) {
                    specifiers.push(with_ext);
                }
                if !specifiers.contains(&without_ext) {
                    specifiers.push(without_ext);
                }
            }
        }
    }

    specifiers
}

/// Match a glob pattern against a filename (last path component).
/// Supports `*` as a wildcard within the filename. Does not match path separators.
/// Examples: `*.py`, `test_*`, `*_test.rs`, `*`
pub(in crate::mcp) fn glob_filename_matches(pattern: &str, filename: &str) -> bool {
    if pattern == "*" {
        return true;
    }
    if !pattern.contains('*') {
        return filename == pattern;
    }
    // Split on the first `*` and check prefix + suffix
    let (prefix, rest) = pattern.split_once('*').unwrap();
    if !filename.starts_with(prefix) {
        return false;
    }
    let after_prefix = &filename[prefix.len()..];
    // Handle remaining pattern segments (multiple `*`)
    if rest.contains('*') {
        // Recursively match the remainder
        glob_filename_matches(rest, after_prefix)
    } else {
        // Single `*` — remainder is a literal suffix
        after_prefix.ends_with(rest) && after_prefix.len() >= rest.len()
    }
}

/// Compute directory rollup for group_by="subdir" and format the result.
pub(in crate::mcp) fn build_rollup(
    entries: Vec<(&str, usize, usize)>,
    prefix: Option<&str>,
    sort_by: &str,
    order: Option<&str>,
) -> String {
    let total_files = entries.len();
    let total_loc: usize = entries.iter().map(|(_, loc, _)| loc).sum();
    let bucket_vec = fmm_core::format::compute_rollup_buckets(&entries, prefix, sort_by, order);
    fmm_core::format::format_list_files_rollup(prefix, &bucket_vec, total_files, total_loc)
}
