// AUTO-GENERATED by build.rs from tools.toml — do not edit
#![allow(clippy::all)]
#[rustfmt::skip]

pub fn generated_tool_list() -> serde_json::Value {
serde_json::from_str(r##"{
  "tools": [
    {
      "name": "fmm_lookup_export",
      "description": "Instant O(1) symbol-to-file lookup. Find where a function, class, type, or variable is defined. Returns the file path plus metadata (exports, imports, dependencies, LOC). Use before Grep.",
      "inputSchema": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "Exact export name to find (function, class, type, variable, component)"
          }
        },
        "required": [
          "name"
        ]
      }
    },
    {
      "name": "fmm_list_exports",
      "description": "Search or list exported symbols across the codebase. Use 'pattern' for fuzzy discovery (e.g. 'auth' matches validateAuth, authMiddleware). Patterns with regex metacharacters (^, $, [, (, \\\\, ., *, +, ?, {) are compiled as regex. Use 'directory' to scope results to a path prefix (e.g. 'packages/core/'). Use 'file' to list a specific file's exports. Default limit: 200. Use offset to page through large result sets.",
      "inputSchema": {
        "type": "object",
        "properties": {
          "pattern": {
            "type": "string",
            "description": "Pattern to match against export names. Plain strings use case-insensitive substring match (e.g. 'auth' finds validateAuth, authMiddleware). Patterns containing regex metacharacters (^, $, [, (, \\\\, ., *, +, ?, {) are compiled as regex: '^handle' = prefix match, 'Service$' = suffix match, '^[A-Z]' = PascalCase only. Invalid regex returns an error."
          },
          "file": {
            "type": "string",
            "description": "File path — returns all exports from this specific file"
          },
          "directory": {
            "type": "string",
            "description": "Path prefix to scope results (e.g. 'packages/core/'). Only exports from files under this directory are returned."
          },
          "limit": {
            "type": "integer",
            "description": "Maximum number of results to return (default: 200). Increase for broader listings."
          },
          "offset": {
            "type": "integer",
            "description": "Number of results to skip before returning (default: 0). Use for pagination: offset=200 returns results 201–400."
          }
        }
      }
    },
    {
      "name": "fmm_dependency_graph",
      "description": "Get a file's dependency graph: upstream dependencies (what it imports) and downstream dependents (what would break if it changes). Use for impact analysis and blast radius. Add depth>1 for transitive traversal; depth=-1 for full closure. Use filter='source' to exclude test files from downstream, or filter='tests' to see only test coverage.",
      "inputSchema": {
        "type": "object",
        "properties": {
          "file": {
            "type": "string",
            "description": "File path to analyze — returns all upstream dependencies and downstream dependents"
          },
          "depth": {
            "type": "integer",
            "description": "Traversal depth (default: 1 = direct deps only). depth=2 adds transitive deps. depth=-1 computes the full transitive closure. depth>1 returns flat lists with a depth annotation per entry."
          },
          "filter": {
            "type": "string",
            "description": "Filter upstream and downstream lists by file type. 'all' (default): no filtering. 'source': exclude test files (*.spec.ts, *.test.ts, /test/, etc.) — use for production blast-radius analysis. 'tests': show only test files — use for test coverage analysis.",
            "enum": [
              "all",
              "source",
              "tests"
            ]
          }
        },
        "required": [
          "file"
        ]
      }
    },
    {
      "name": "fmm_read_symbol",
      "description": "Read the source code for a specific exported symbol. Returns the exact lines where the function/class/type is defined, without reading the entire file. Requires line-range data from v0.3 sidecars. Use `ClassName.method` notation to read a specific public or private method: `fmm_read_symbol(name: \"Injector.loadInstance\")`. Use `path/to/file.ts:helperFunction` notation to read a non-exported top-level function via on-demand tree-sitter parse. Private methods discovered via fmm_file_outline(include_private: true) are accessible using the same dotted notation. For large symbols (>10KB) use truncate: false to get the full source. Use line_numbers: true to prepend absolute line numbers to each source line.",
      "inputSchema": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "Exact export name to read (function, class, type, component), or ClassName.method for a specific public or private method, or path/to/file.ts:helperFn to read a non-exported top-level function by on-demand parse"
          },
          "truncate": {
            "type": "boolean",
            "description": "Whether to apply the 10KB response cap (default: true). Set to false to return the full source for large symbols that would otherwise be truncated."
          },
          "line_numbers": {
            "type": "boolean",
            "description": "When true, prepend absolute line numbers (right-aligned) to each source line. Useful when referencing specific lines in follow-up questions. Default: false."
          }
        },
        "required": [
          "name"
        ]
      }
    },
    {
      "name": "fmm_file_outline",
      "description": "Get a spatial outline of a file: every exported symbol with its line range and size. Like a table-of-contents for the file. Use to understand file structure before reading specific symbols. Set include_private: true to also show private/protected class members AND non-exported top-level functions (in a 'non_exported:' section). Supported: TypeScript, JavaScript, Python. On-demand tree-sitter parse — no index rebuild needed.",
      "inputSchema": {
        "type": "object",
        "properties": {
          "file": {
            "type": "string",
            "description": "File path to outline — returns all exports with line ranges and sizes"
          },
          "include_private": {
            "type": "boolean",
            "description": "When true, include private/protected members under each class (annotated '# private') AND non-exported top-level functions in a 'non_exported:' section (annotated '# non-exported'). On-demand tree-sitter parse — no index rebuild needed. Supported: TypeScript, JavaScript, Python. Default: false."
          }
        },
        "required": [
          "file"
        ]
      }
    },
    {
      "name": "fmm_search",
      "description": "Universal codebase search. Use 'term' for smart search across codebase-defined exports, file paths, import package names, and named-import call sites. The NAMED IMPORTS section shows files that import the term by name from any package — e.g. term: createServerFn finds every file that imports createServerFn from @tanstack/react-start. Use structured filters (export, imports, depends_on, LOC) for precise queries. Combine 'term' with filters to narrow results with AND semantics. Note: depends_on uses transitive matching (full import chain), not direct-only. For direct importers only, use fmm_dependency_graph with depth=1.",
      "inputSchema": {
        "type": "object",
        "properties": {
          "term": {
            "type": "string",
            "description": "Search codebase-defined exports (exact then fuzzy), file paths, external import package names, and named-import call sites. Results appear in four sections: EXPORTS (locally defined symbols), FILES (matching paths), IMPORTS (packages), and NAMED IMPORTS (files that import the term by name from any external package). Can be combined with structured filters to narrow results to matching files."
          },
          "export": {
            "type": "string",
            "description": "Find files exporting this symbol (exact match, then case-insensitive substring fallback)"
          },
          "imports": {
            "type": "string",
            "description": "Find all files that import an external package (npm, pip, crate, etc.) — substring match on the import name. For local file paths (e.g. src/db/client), use depends_on instead."
          },
          "depends_on": {
            "type": "string",
            "description": "Find all files that transitively depend on this local path (full import chain, not just direct importers) — use for full blast radius before renaming. For direct-only importers, use fmm_dependency_graph with depth=1."
          },
          "min_loc": {
            "type": "integer",
            "description": "Minimum lines of code — find files larger than this"
          },
          "max_loc": {
            "type": "integer",
            "description": "Maximum lines of code — find files smaller than this"
          },
          "limit": {
            "type": "integer",
            "description": "Maximum number of fuzzy export results (default: 50). Increase for broader searches."
          }
        }
      }
    },
    {
      "name": "fmm_list_files",
      "description": "List all indexed files under a directory prefix. The first tool to reach for when exploring an unknown module or package. Returns file paths with LOC, export count, and downstream dependent count. Default sort: LOC descending (largest files first). sort_by options: loc (default), name, exports, downstream (blast-radius sort), modified (most recently changed first). Default limit: 200. Use offset to page through large directories.",
      "inputSchema": {
        "type": "object",
        "properties": {
          "directory": {
            "type": "string",
            "description": "Directory prefix to filter files (e.g. 'src/cli/' or 'libs/agno/models'). Omit to list all indexed files."
          },
          "pattern": {
            "type": "string",
            "description": "Glob pattern to filter by filename within the directory (e.g. '*.py', '*.rs', 'test_*'). Supports * wildcard."
          },
          "limit": {
            "type": "integer",
            "description": "Maximum number of files to return (default: 200). Increase for broader listings."
          },
          "offset": {
            "type": "integer",
            "description": "Number of files to skip before returning results (default: 0). Use for pagination: offset=200 returns files 201–400."
          },
          "sort_by": {
            "type": "string",
            "description": "Sort field. 'loc' (default): lines of code descending. 'name': alphabetical. 'exports': export count descending. 'downstream': direct dependent count descending (blast-radius sort — highest-risk files first). 'modified': most recently changed files first (date shown in output). 'loc', 'exports', 'downstream', and 'modified' default to descending order.",
            "enum": [
              "name",
              "loc",
              "exports",
              "downstream",
              "modified"
            ]
          },
          "order": {
            "type": "string",
            "description": "Sort order. Defaults: 'name' → asc, 'loc'/'exports'/'downstream' → desc. Explicit 'asc'/'desc' overrides the default.",
            "enum": [
              "asc",
              "desc"
            ]
          },
          "group_by": {
            "type": "string",
            "description": "Collapse files into directory buckets. 'subdir': group by immediate subdirectory, showing file count and total LOC per bucket. Best for initial orientation of large codebases. sort_by applies to bucket-level LOC.",
            "enum": [
              "subdir"
            ]
          },
          "filter": {
            "type": "string",
            "description": "File type filter. 'all' (default): no filtering. 'source': exclude test files. 'tests': return only test files. Detection heuristic uses path segments (/test/, /e2e/, /__tests__/) and filename suffixes (.spec.ts, .test.ts, _test.go, etc.), configurable via test_patterns in .fmmrc.json.",
            "enum": [
              "all",
              "source",
              "tests"
            ]
          }
        }
      }
    },
    {
      "name": "fmm_glossary",
      "description": "Symbol-level impact analysis. Given a symbol name or pattern, returns all definitions and exactly which files import each one. Three-layer precision: bare name returns named-import filtered callers (Layer 2, default); dotted name (e.g. 'Injector.loadInstance') adds call-site precision; precision: 'call-site' adds Layer 3 tree-sitter to remove dead imports and annotate re-exports. Use before renaming or changing a signature.",
      "inputSchema": {
        "type": "object",
        "properties": {
          "pattern": {
            "type": "string",
            "description": "Required. Case-insensitive substring filter on export name. Bare name (e.g. 'loadInstance') returns named-import filtered used_by (Layer 2). Dotted name (e.g. 'Injector.loadInstance') adds call-site precision, filtered to actual callers."
          },
          "limit": {
            "type": "integer",
            "description": "Max entries returned (default 10, hard cap at 50). Use a specific pattern to stay under the default."
          },
          "mode": {
            "type": "string",
            "description": "source (default): excludes test symbols and test files. tests: only test exports. all: unfiltered.",
            "enum": [
              "source",
              "tests",
              "all"
            ]
          },
          "precision": {
            "type": "string",
            "description": "named (default): Layer 2 only, fast index lookup with no file reads. call-site: adds Layer 3 tree-sitter verification to remove dead imports and annotate re-export-only files.",
            "enum": [
              "named",
              "call-site"
            ]
          }
        },
        "required": [
          "pattern"
        ]
      }
    }
  ]
}"##).expect("generated tool list is valid JSON")
}
