// AUTO-GENERATED by build.rs from tools.toml — do not edit
#![allow(clippy::all)]
#[rustfmt::skip]

pub fn generated_tool_list() -> serde_json::Value {
serde_json::from_str(r##"{
  "tools": [
    {
      "name": "fmm_lookup_export",
      "description": "Instant O(1) symbol-to-file lookup. Find where a function, class, type, or variable is defined. Returns the file path plus metadata (exports, imports, dependencies, LOC). Use before Grep.",
      "inputSchema": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "Exact export name to find (function, class, struct, type, trait, variable)"
          }
        },
        "required": [
          "name"
        ]
      }
    },
    {
      "name": "fmm_list_exports",
      "description": "Search or list exported symbols across the codebase. Use 'pattern' for fuzzy discovery (e.g. 'auth' matches validateAuth, authMiddleware). Patterns with regex metacharacters (^, $, [, (, \\\\, ., *, +, ?, {) are compiled as regex. Use 'directory' to scope results to a path prefix (e.g. 'packages/core/'). Use 'file' to list a specific file's exports. Use filter='source' to exclude test files, or filter='tests' to show only test exports. Default limit: 200. Use offset to page through large result sets.",
      "inputSchema": {
        "type": "object",
        "properties": {
          "pattern": {
            "type": "string",
            "description": "Pattern to match against export names. Plain strings use case-insensitive substring match (e.g. 'auth' finds validateAuth, authMiddleware). Patterns containing regex metacharacters (^, $, [, (, \\\\, ., *, +, ?, {) are compiled as regex: '^handle' = prefix match, 'Service$' = suffix match, '^[A-Z]' = PascalCase only. Invalid regex returns an error."
          },
          "file": {
            "type": "string",
            "description": "File path — returns all exports from this specific file"
          },
          "directory": {
            "type": "string",
            "description": "Path prefix to scope results (e.g. 'packages/core/'). Only exports from files under this directory are returned."
          },
          "filter": {
            "type": "string",
            "description": "File type filter. 'all' (default): no filtering. 'source': exclude test files using the same path and filename conventions as fmm_list_files. 'tests': return only test files.",
            "enum": [
              "all",
              "source",
              "tests"
            ]
          },
          "limit": {
            "type": "integer",
            "description": "Maximum number of results to return (default: 200). Increase for broader listings."
          },
          "offset": {
            "type": "integer",
            "description": "Number of results to skip before returning (default: 0). Use for pagination: offset=200 returns results 201–400."
          }
        }
      }
    },
    {
      "name": "fmm_dependency_graph",
      "description": "Get a file's dependency graph: upstream dependencies (what it imports) and downstream dependents (what would break if it changes). Use for impact analysis and blast radius. Add depth>1 for transitive traversal; depth=-1 for full closure. Use filter='source' to exclude test files from downstream, or filter='tests' to see only test coverage.",
      "inputSchema": {
        "type": "object",
        "properties": {
          "file": {
            "type": "string",
            "description": "File path to analyze — returns all upstream dependencies and downstream dependents"
          },
          "depth": {
            "type": "integer",
            "description": "Traversal depth (default: 1 = direct deps only). depth=2 adds transitive deps. depth=-1 computes the full transitive closure. depth>1 returns flat lists with a depth annotation per entry."
          },
          "filter": {
            "type": "string",
            "description": "Filter upstream and downstream lists by file type. 'all' (default): no filtering. 'source': exclude test files (*.spec.ts, *.test.ts, /test/, etc.) — use for production blast-radius analysis. 'tests': show only test files — use for test coverage analysis.",
            "enum": [
              "all",
              "source",
              "tests"
            ]
          }
        },
        "required": [
          "file"
        ]
      }
    },
    {
      "name": "fmm_dependency_cycles",
      "description": "Report strongly connected dependency cycles over the internal graph. Defaults to runtime edges, excluding TypeScript type-only imports and module-hierarchy facade edges. Use edge_mode='all' to include type-only edges. Set include_mod_hierarchy=true to restore facade edges. Set explain=true to include the edges that keep each SCC connected. Optional file scopes output to cycles containing that file. filter='source' excludes tests, filter='tests' shows only test files.",
      "inputSchema": {
        "type": "object",
        "properties": {
          "file": {
            "type": "string",
            "description": "Optional file path to scope cycle reports to SCCs containing that file."
          },
          "filter": {
            "type": "string",
            "description": "Filter the cycle graph by file type before SCC detection. 'all' (default): no filtering. 'source': exclude test files. 'tests': show only test files.",
            "enum": [
              "all",
              "source",
              "tests"
            ]
          },
          "edge_mode": {
            "type": "string",
            "description": "Edge mode for cycle reporting. 'runtime' (default) excludes TypeScript type-only edges. 'all' includes type-only edges.",
            "enum": [
              "runtime",
              "all"
            ]
          },
          "include_mod_hierarchy": {
            "type": "boolean",
            "description": "When true, include module-hierarchy facade edges. Default false hides barrel, __init__, and Rust module facade cycles."
          },
          "explain": {
            "type": "boolean",
            "description": "When true, include the resolved edges that keep each reported strongly connected component connected, with edge kind."
          }
        }
      }
    },
    {
      "name": "fmm_read_symbol",
      "description": "Read the source code for a specific exported symbol or uniquely named non-exported top-level function. Returns the exact lines where the function/class/type/member is defined, without reading the entire file. Use `ClassName.member` notation to read a specific public/private method or indexed field: `fmm_read_symbol(name: \"Injector.loadInstance\")`. Bare Rust module names return the `mod foo;` declaration with `kind: module`; they do not follow into `foo.rs` or `foo/mod.rs`. Use `path/to/file:helperFunction` notation to disambiguate duplicate exports or duplicate non-exported top-level functions. Private methods discovered via fmm_file_outline(include_private: true) are accessible using the same dotted notation. For large symbols (>10KB) use truncate: false to get the full source. Use line_numbers: true to prepend absolute line numbers to each source line.",
      "inputSchema": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "Exact symbol name to read (function, class, struct, type, trait), ClassName.method for a specific public or private method, or path/to/file:helperFn to disambiguate duplicate exports or non-exported top-level functions"
          },
          "truncate": {
            "type": "boolean",
            "description": "Whether to apply the 10KB response cap (default: true). Set to false to return the full source for large symbols that would otherwise be truncated."
          },
          "line_numbers": {
            "type": "boolean",
            "description": "When true, prepend absolute line numbers (right-aligned) to each source line. Useful when referencing specific lines in follow-up questions. Default: false."
          }
        },
        "required": [
          "name"
        ]
      }
    },
    {
      "name": "fmm_file_outline",
      "description": "Get a spatial outline of a file: symbols with line ranges, size, signature, visibility, and kind when populated. Like a table-of-contents for the file. Use to understand file structure before reading specific symbols. Set include_private: true to add on-demand private members not already indexed plus non-exported top-level declarations inline in symbols. Stale queried files include one inline freshness annotation. Supported: TypeScript, JavaScript, Python, Rust. On-demand tree-sitter parse for private additions; no index rebuild needed.",
      "inputSchema": {
        "type": "object",
        "properties": {
          "file": {
            "type": "string",
            "description": "File path to outline — returns symbols with line ranges, sizes, signatures, visibility, and kind when populated"
          },
          "include_private": {
            "type": "boolean",
            "description": "When true, add on-demand private members not already indexed plus non-exported top-level declarations inline in symbols with explicit visibility and kind rows. On-demand tree-sitter parse; no index rebuild needed. Supported: TypeScript, JavaScript, Python, Rust. Default: false."
          },
          "truncate": {
            "type": "boolean",
            "description": "When false, bypasses the 10KB MCP response cap and returns the full outline response. Default: true."
          }
        },
        "required": [
          "file"
        ]
      }
    },
    {
      "name": "fmm_search",
      "description": "Universal codebase search. Use 'term' for smart search across codebase-defined exports, file paths, import package names, and named-import call sites. The NAMED IMPORTS section shows files that import the term by name from any package — e.g. term: createServerFn finds every file that imports createServerFn from @tanstack/react-start. Use structured filters (export, imports, depends_on, LOC) for precise queries. Combine 'term' with filters to narrow results with AND semantics. Note: depends_on uses transitive matching (full import chain), not direct-only. For direct importers only, use fmm_dependency_graph with depth=1.",
      "inputSchema": {
        "type": "object",
        "properties": {
          "term": {
            "type": "string",
            "description": "Search codebase-defined exports (exact then fuzzy), file paths, external import package names, and named-import call sites. Results appear in four sections: EXPORTS (locally defined symbols), FILES (matching paths), IMPORTS (packages), and NAMED IMPORTS (files that import the term by name from any external package). Can be combined with structured filters to narrow results to matching files."
          },
          "export": {
            "type": "string",
            "description": "Find files exporting this symbol (exact match, then case-insensitive substring fallback)"
          },
          "imports": {
            "type": "string",
            "description": "Find all files that import an external package (npm, pip, crate, etc.) — substring match on the import name. For local file paths (e.g. src/db/client), use depends_on instead."
          },
          "depends_on": {
            "type": "string",
            "description": "Find all files that transitively depend on this local path (full import chain, not just direct importers) — use for full blast radius before renaming. For direct-only importers, use fmm_dependency_graph with depth=1."
          },
          "min_loc": {
            "type": "integer",
            "description": "Minimum lines of code — find files larger than this"
          },
          "max_loc": {
            "type": "integer",
            "description": "Maximum lines of code — find files smaller than this"
          },
          "limit": {
            "type": "integer",
            "description": "Maximum number of fuzzy export results (default: 50). Increase for broader searches."
          }
        }
      }
    },
    {
      "name": "fmm_list_files",
      "description": "List all indexed files under a directory prefix. The first tool to reach for when exploring an unknown module or package. Returns file paths with LOC, export count, and downstream dependent count. Default sort: LOC descending (largest files first). sort_by options: loc (default), name/path, exports, downstream (blast-radius sort), modified (most recently changed first). Default limit: 200. Use offset to page through large directories.",
      "inputSchema": {
        "type": "object",
        "properties": {
          "directory": {
            "type": "string",
            "description": "Directory prefix to filter files (e.g. 'src/cli/' or 'libs/agno/models'). Omit to list all indexed files."
          },
          "pattern": {
            "type": "string",
            "description": "Shell-style glob pattern to filter by filename within the directory (e.g. '*.py', '*test*', 'file?.rs', '[ab]*.ts'). Matches filenames only, not full paths."
          },
          "limit": {
            "type": "integer",
            "description": "Maximum number of files to return (default: 200). Increase for broader listings."
          },
          "offset": {
            "type": "integer",
            "description": "Number of files to skip before returning results (default: 0). Use for pagination: offset=200 returns files 201–400."
          },
          "sort_by": {
            "type": "string",
            "description": "Sort field. 'loc' (default): lines of code descending. 'name' or 'path': alphabetical file path. 'exports': export count descending. 'downstream': direct dependent count descending (blast-radius sort, highest-risk files first). 'modified': most recently changed files first (date shown in output). 'loc', 'exports', 'downstream', and 'modified' default to descending order.",
            "enum": [
              "name",
              "path",
              "loc",
              "exports",
              "downstream",
              "modified"
            ]
          },
          "order": {
            "type": "string",
            "description": "Sort order. Defaults: 'name' → asc, 'loc'/'exports'/'downstream' → desc. Explicit 'asc'/'desc' overrides the default.",
            "enum": [
              "asc",
              "desc"
            ]
          },
          "group_by": {
            "type": "string",
            "description": "Collapse files into directory buckets. 'subdir': group by immediate subdirectory, showing file count and total LOC per bucket. Best for initial orientation of large codebases. sort_by applies to bucket-level LOC.",
            "enum": [
              "subdir"
            ]
          },
          "filter": {
            "type": "string",
            "description": "File type filter. 'all' (default): no filtering. 'source': exclude test files. 'tests': return only files classified as tests by path or filename. Detection uses path segments (/test/, /e2e/, /__tests__/) and filename suffixes (.spec.ts, .test.ts, _test.go, *_tests.rs, tests.rs, etc.), configurable via test_patterns in .fmmrc.toml. Rust inline #[cfg(test)] mod tests blocks inside ordinary source files do not make the containing file a test file.",
            "enum": [
              "all",
              "source",
              "tests"
            ]
          }
        }
      }
    },
    {
      "name": "fmm_glossary",
      "description": "Symbol-level impact analysis. Given a symbol name or pattern, returns all matching definitions and exactly which files import each one. Three-layer precision: bare names return named-import filtered callers (Layer 2, default); dotted method names (e.g. 'Injector.loadInstance') add call-site precision; dotted patterns use the same case-insensitive substring matching, so 'Type.foo' can match both 'Type.foo' and 'Type.foo_bar'. Dotted field names report kind: field without implying method callers; precision: 'call-site' adds Layer 3 tree-sitter verification to remove dead imports and annotate re-exports. Use before renaming or changing a signature.",
      "inputSchema": {
        "type": "object",
        "properties": {
          "pattern": {
            "type": "string",
            "description": "Required. Case-insensitive substring filter on export name. Bare name (e.g. 'loadInstance') returns named-import filtered used_by (Layer 2). Dotted method name (e.g. 'Injector.loadInstance') adds call-site precision, filtered to actual callers, and matches on the full dotted name as a substring, so 'Type.foo' can match 'Type.foo' and 'Type.foo_bar'. Dotted field name emits kind: field and does not imply a method call site."
          },
          "limit": {
            "type": "integer",
            "description": "Max entries returned (default 10, hard cap at 50). Use a specific pattern to stay under the default."
          },
          "mode": {
            "type": "string",
            "description": "source (default): excludes test symbols and test files. tests: only test exports. all: unfiltered.",
            "enum": [
              "source",
              "tests",
              "all"
            ]
          },
          "precision": {
            "type": "string",
            "description": "named (default): Layer 2 only, fast index lookup with no file reads. call-site: adds Layer 3 tree-sitter verification to remove dead imports and annotate re-export-only files.",
            "enum": [
              "named",
              "call-site"
            ]
          },
          "truncate": {
            "type": "boolean",
            "description": "Whether to apply the 10KB response cap (default: true). Set to false to return the full glossary for symbols with many callers."
          }
        },
        "required": [
          "pattern"
        ]
      }
    },
    {
      "name": "fmm_find_similar",
      "description": "Find existing functions or types structurally similar to a probe, before writing new code, to prevent duplication. Probe by an existing symbol name, or supply a signature + kind for a symbol you are about to write. Deterministic: ranks by name-token overlap, signature shape, declaration kind, and shared-dependency neighborhood — no embeddings. Results are threshold-gated, so a probe with one real match returns one row. Use before authoring a new symbol to reuse instead of duplicate.",
      "inputSchema": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "Probe symbol name. In by-symbol mode this is an existing symbol whose signature and kind seed the probe; in pre-write mode it is the name you intend to use."
          },
          "signature": {
            "type": "string",
            "description": "Explicit signature for the symbol you are about to write, e.g. '(Path) -> Config'. Overrides the looked-up signature when probing by an existing name."
          },
          "kind": {
            "type": "string",
            "description": "Declaration kind to match: fn, method, struct, trait, enum, type, const."
          },
          "directory": {
            "type": "string",
            "description": "Path prefix to scope candidates (e.g. 'crates/fmm-core/')."
          },
          "limit": {
            "type": "integer",
            "description": "Maximum matches to return (default: 10). Results are threshold-gated, so fewer may return."
          },
          "include_tests": {
            "type": "boolean",
            "description": "Include test functions and modules as candidates (default: false)."
          }
        },
        "required": [
          "name"
        ]
      }
    },
    {
      "name": "fmm_dupe_clusters",
      "description": "Find repo wide structural duplicate candidate clusters by reusing the find similar ranker in batch mode. Deterministic: blocks candidates by declaration kind, rare name tokens, and signature shape, scores unique unordered pairs with the existing structural scorer, then union-finds accepted pairs into clusters.",
      "inputSchema": {
        "type": "object",
        "properties": {
          "directory": {
            "type": "string",
            "description": "Path prefix to scope candidates (e.g. 'crates/fmm-core/')."
          },
          "kind": {
            "type": "array",
            "description": "Declaration kinds to include. Repeat --kind in the CLI. Typical values: fn, method, struct, trait, enum, type, const."
          },
          "min_score": {
            "type": "number",
            "description": "Minimum pair score required to join a cluster. Defaults to the same threshold as fmm similar."
          },
          "limit": {
            "type": "integer",
            "description": "Maximum clusters to return (default: 10)."
          },
          "include_tests": {
            "type": "boolean",
            "description": "Include test functions and modules as candidates (default: false)."
          }
        }
      }
    }
  ]
}"##).expect("generated tool list is valid JSON")
}
